# Generated by Django 5.1.3 on 2024-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('long_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poster', models.URLField(blank=True, null=True)),
                ('image_local', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('rating', models.FloatField(default=0.0)),
                ('in_stock', models.BooleanField(default=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('best_seller', models.BooleanField(default=False)),
            ],
        ),
    ]
