# Generated by Django 5.1.3 on 2024-11-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstorebackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='bookstorebackend_products',
        ),
    ]
