version: '3.9'

services:
  backend:
    build:
      context: ./bookstorebackend
      dockerfile: Dockerfile
    container_name: bookstore-backend
    ports:
      - "8000:8000"
    volumes:
      - ./bookstorebackend:/app            # Sync code changes
      - ./bookstorebackend/db.sqlite3:/app/db.sqlite3  # Persist database
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: bookstore-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
