version: '3.9'

services:
  web:
    build:
      context: .  # Use the project root as the context
      dockerfile: bookstorebackend/Dockerfile
    container_name: bookstore-backend
    working_dir: /app  # Set the working directory to /app
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/app  # Map the project root to /app inside the container
      - sqlite-data:/app/db  # Persist the SQLite database
    ports:
      - "8000:8000"

  web_migrate:
    extends:
      service: web
    command: python manage.py migrate

  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: bookstore-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - web_run

  sqlite:
    image: nouchka/sqlite3:latest
    container_name: sqlite-container
    volumes:
      - sqlite-data:/mydatabase
    command: tail -f /dev/null

volumes:
  sqlite-data:
